void show_mainwindow(void);
void hide_mainwindow(void);

enum {
  THERMOSTAT_INDEX_KEY,
  THERMOSTAT_ID_KEY,
  THERMOSTAT_NAME_KEY,
  THERMOSTAT_TEMPERATURE_KEY,
  THERMOSTAT_TARGET_TEMPERATURE_KEY,
  TEMPERATURE_CHANGE_KEY
};